server:
  port: 19102
spring:
  application:
    name: personal-records-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/genuniv_precord
    username: postgres
    password: password
    maximum-pool-size: 50
    driver-class-name: org.postgresql.Driver
#  jpa:
#    show-sql: true
#  flyway:
#    clean-on-validation-error: true
intra:
  service:
    College:
      protocol: http
      service-name: college-service
      CollegeApi:
        api-prefix: /api/v1/college
      DegreeApi:
        api-prefix: /api/v1/degree
      DegreeTypeApi:
        api-prefix: /api/v1/degree-type
      CourseApi:
        api-prefix: /api/v1/course
loading-cache:
  slow-interval: 30
  fast-interval: 15